// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/davidterranova/contacts/internal/contacts/usecase (interfaces: ContactCmdHandler)
//
// Generated by this command:
//    mockgen -destination=mock_contact_cmd_handler.go -package=usecase . ContactCmdHandler
// Package usecase is a generated GoMock package.
package usecase

import (
        reflect "reflect"
        context "context"
        domain "github.com/davidterranova/contacts/internal/contacts/domain"
        eventsourcing "github.com/davidterranova/cqrs/eventsourcing"
        uuid "github.com/google/uuid"
        gomock "go.uber.org/mock/gomock"
)

// MockContactCmdHandler is a mock of ContactCmdHandler interface.
type MockContactCmdHandler struct {
        ctrl     *gomock.Controller
        recorder *MockContactCmdHandlerMockRecorder
}

// MockContactCmdHandlerMockRecorder is the mock recorder for MockContactCmdHandler.
type MockContactCmdHandlerMockRecorder struct {
        mock *MockContactCmdHandler
}

// NewMockContactCmdHandler creates a new mock instance.
func NewMockContactCmdHandler(ctrl *gomock.Controller) *MockContactCmdHandler {
        mock := &MockContactCmdHandler{ctrl: ctrl}
        mock.recorder = &MockContactCmdHandlerMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactCmdHandler) EXPECT() *MockContactCmdHandlerMockRecorder {
        return m.recorder
}

// HandleCommand mocks base method.
func (m *MockContactCmdHandler) HandleCommand(arg0 context.Context, arg1 eventsourcing.Command[domain.Contact]) (*domain.Contact, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "HandleCommand", arg0, arg1)
        ret0, _ := ret[0].(*domain.Contact)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// HandleCommand indicates an expected call of HandleCommand.
func (mr *MockContactCmdHandlerMockRecorder) HandleCommand(arg0, arg1 any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCommand", reflect.TypeOf((*MockContactCmdHandler)(nil).HandleCommand), arg0, arg1)
}

// HydrateAggregate mocks base method.
func (m *MockContactCmdHandler) HydrateAggregate(arg0 context.Context, arg1 eventsourcing.AggregateType, arg2 uuid.UUID) (*domain.Contact, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "HydrateAggregate", arg0, arg1, arg2)
        ret0, _ := ret[0].(*domain.Contact)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// HydrateAggregate indicates an expected call of HydrateAggregate.
func (mr *MockContactCmdHandlerMockRecorder) HydrateAggregate(arg0, arg1, arg2 any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HydrateAggregate", reflect.TypeOf((*MockContactCmdHandler)(nil).HydrateAggregate), arg0, arg1, arg2)
}
