name: Go package
on:
  push:
    branches:
      - "*"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.2'
          cache: false
      - name: Test
        run: make test-unit
